authors:
  Lassulus:
    name: "Lassulus"
    description: "Contributor to Clan"
    avatar: "https://avatars.githubusercontent.com/u/621759?v=4"
    url: "https://http://lassul.us/"
  Mic92:
    name: "Mic92"
    description: "Contributor to Clan"
    avatar: "https://avatars.githubusercontent.com/u/96200?v=4"
    url: "https://thalheim.io"
  W:
    name: "W"
    description: "Founder of Clan"
    avatar: "/static/w_profile.webp"
    url: ""
  Qubasa:
    name: "Qubasa"
    description: "Contributor to Clan"
    avatar: "https://avatars.githubusercontent.com/u/22085373?v=4"
    url: "https://github.com/Qubasa"