authors:
  DavHau:
    name: "DavHau"
    description: "Core Developer"
    avatar: "https://clan.lol/static/profiles/davhau.jpg"
    url: "https://DavHau.com"
  Lassulus:
    name: "Lassulus"
    description: "Core Developer"
    avatar: "https://clan.lol/static/profiles/lassulus.jpg"
    url: "https://http://lassul.us/"
  Mic92:
    name: "Mic92"
    description: "Core Developer"
    avatar: "https://clan.lol/static/profiles/mic92.jpg"
    url: "https://thalheim.io"
  W:
    name: "W"
    description: "Founder of Clan"
    avatar: "https://clan.lol/static/profiles/w_profile.webp"
    url: ""
  Qubasa:
    name: "Qubasa"
    description: "Core Developer"
    avatar: "https://clan.lol/static/profiles/qubasa.png"
    url: "https://github.com/Qubasa"
  BrianMcGee:
    name: "Brian McGee"
    description: "Contributor"
    avatar: "https://avatars.githubusercontent.com/u/1173648?v=4"
    url: "https://bmcgee.ie"
