[tool.mypy]
python_version = "3.10"
pretty = true
warn_redundant_casts = true
disallow_untyped_calls = true
disallow_untyped_defs = true
no_implicit_optional = true
exclude = "clan_cli.nixpkgs"

[tool.ruff]
line-length = 88

select = [ "E", "F", "I", "U", "N"]
ignore = [ "E501" ]
