name: checks
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  checks-impure:
    runs-on: nix
    steps:
      - uses: actions/checkout@v3
      - run: nix run .#impure-checks
  deploy-docs:
    runs-on: nix
    steps:
      - uses: actions/checkout@v3
      - run: nix run .#deploy-docs
    env:
      SSH_HOMEPAGE_KEY: ${{ secrets.SSH_HOMEPAGE_KEY }}