name: "Update pinned clan-core for checks"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "51 2 * * *"
jobs:
  update-pinned-clan-core:
    runs-on: nix
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update clan-core for checks
        run: nix run .#update-clan-core-for-checks
      - name: Create pull request
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
        run: |
          export GIT_AUTHOR_NAME=clan-bot GIT_AUTHOR_EMAIL=clan-bot@clan.lol GIT_COMMITTER_NAME=clan-bot GIT_COMMITTER_EMAIL=clan-bot@clan.lol
          git commit -am "Update pinned clan-core for checks"
          git push origin +HEAD:update-clan-core-for-checks
          set -x
          nix run --inputs-from . nixpkgs#curl -- -X POST \
            -H "Authorization: token $GITEA_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "head": "update-clan-core-branch",
              "base": "main",
              "title": "Automated Update: Clan Core",
              "body": "This PR updates the pinned clan-core for checks."
            }' \
           "https://git.clan.lol/api/v1/repos/clan/clan-core/pulls"
