name: Update Flake Inputs

on:
  schedule:
    # Run every 5 hours
    - cron: "0 */5 * * *"
  workflow_dispatch:
  repository_dispatch:

jobs:
  update-flake-inputs:
    runs-on: nix
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --global user.email "clan-bot@clan.lol"
          git config --global user.name "clan-bot"

      - name: Update flake inputs
        uses: Mic92/update-flake-inputs-gitea@main
        with:
          # Exclude private flakes and update-clan-core checks flake

          exclude-patterns: "devFlake/private/flake.nix,checks/impure/flake.nix"
          auto-merge: true
          gitea-token: ${{ secrets.CI_BOT_TOKEN }}
          github-token: ${{ secrets.CI_BOT_GITHUB_TOKEN }}
