version: "0.5"

processes:
  clan-app-ui:
    command: |
      cd $(git rev-parse --show-toplevel)/pkgs/clan-app/ui
      npm install
      vite
    ready_log_line: "VITE"

  clan-app:
    command: |
      cd $(git rev-parse --show-toplevel)/pkgs/clan-app
      ./bin/clan-app --debug --content-uri http://localhost:3000
    depends_on:
      clan-app-ui:
        condition: "process_log_ready"
    is_foreground: true
    ready_log_line: "Debug mode enabled"
