site_name: cLAN documentation
site_url: https://docs.clan.lol
repo_url: https://git.clan.lol/clan/clan-core/
repo_name: clan-core
edit_uri: _edit/main/docs/docs/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      title: On this page

exclude_docs: |
  .*
  !templates/
  /drafts/

nav:
  - Getting started:
      - index.md
      - Configure: getting-started/configure.md
      - Deploy Machine: getting-started/machines.md
      - Installer: getting-started/installer.md
      - Setup Networking: getting-started/networking.md
      - Provision Secrets & Passwords: getting-started/secrets.md
      - Backup & Restore: getting-started/backups.md
      - Flake-parts: getting-started/flake-parts.md
  - Templates: templates/index.md
  - Reference:
      - ClanCore: reference/clan-core.md
      - ClanModules:
          - reference/borgbackup.md
          - reference/deltachat.md
          - reference/diskLayouts.md
          - reference/ergochat.md
          - reference/graphical.md
          - reference/localbackup.md
          - reference/localsend.md
          - reference/matrix-synapse.md
          - reference/moonlight.md
          - reference/root-password.md
          - reference/sshd.md
          - reference/sunshine.md
          - reference/syncthing.md
          - reference/thelounge.md
          - reference/vm-user.md
          - reference/waypipe.md
          - reference/xfce-vm.md
          - reference/xfce.md
          - reference/zt-tcp-relay.md
  - Contributing: contributing/contributing.md

docs_dir: site
site_dir: out

theme:
  logo: static/logo.png
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - content.code.copy
    - content.tabs.link
  icon:
    repo: fontawesome/brands/git

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      accent: deep purple
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
