[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "clan-vm-manager"
description = "clan vm manager"
dynamic = ["version"]
scripts = { clan-vm-manager = "clan_vm_manager:main" }

[project.urls]
Homepage = "https://clan.lol/"
Documentation = "https://docs.clan.lol/"
Repository = "https://git.clan.lol/clan/clan-core"

[tool.setuptools.packages.find]
exclude = ["result"]

[tool.setuptools.package-data]
clan_vm_manager = ["**/assets/*"]

[tool.pytest.ini_options]
testpaths = "tests"
faulthandler_timeout = 60
log_level = "DEBUG"
log_format = "%(levelname)s: %(message)s\n       %(pathname)s:%(lineno)d::%(funcName)s"
addopts = "--cov . --cov-report term --cov-report html:.reports/html --no-cov-on-fail --durations 5 --color=yes --new-first" # Add --pdb for debugging
norecursedirs = "tests/helpers"
markers = ["impure"]

[tool.mypy]
python_version = "3.12"
warn_redundant_casts = true
disallow_untyped_calls = true
disallow_untyped_defs = true
no_implicit_optional = true

[[tool.mypy.overrides]]
module = "argcomplete.*"
ignore_missing_imports = true
